services:
  xray:
    image: ghcr.io/xtls/xray-core:26.5.9
    container_name: xray-core
    restart: always
    network_mode: host
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
    command: ["run", "-config", "/etc/xray/config.json"]
